apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-textfile
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter:9100']
    - job_name: 'custom-metrics'
      static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'custom'
      file_sd_configs:
      - files:
        - /var/lib/node-exporter-textfile-metrics/*.prom
